# Generated by Django 5.2.1 on 2025-05-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouse_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousemovementsequence',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='mouse_auth.mousemovementsession'),
        ),
    ]
